In [2]:
# Matrix 6x6 with increasing numbers
import numpy as np
A = np.arange(1,37).reshape(6,6)
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [9]:
np.vstack([A[:,:3], A[:,3:]])

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21],
       [25, 26, 27],
       [31, 32, 33],
       [ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24],
       [28, 29, 30],
       [34, 35, 36]])

In [15]:
A = np.arange(1,82).reshape(9,9)
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78, 79, 80, 81]])

In [29]:
A_list = []
for i in range(3):
    A_list.append(A[i*3:(i+1)*3,:])
A_reshaped = np.hstack(A_list)

In [38]:
A_reshaped.T[:3,:].T

array([[ 1,  2,  3],
       [10, 11, 12],
       [19, 20, 21]])